//------------------------------------------------------------------------------
// <auto-generated>
//    This code was generated from a template.
//
//    Manual changes to this file may cause unexpected behavior in your application.
//    Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace Herrd.DataLayer
{
    using System;
    using System.Collections.Generic;
    
    public partial class Track
    {
        public int id { get; set; }
        public int user_id { get; set; }
        public byte[] timestamp { get; set; }
        public string title { get; set; }
        public string term { get; set; }
        public bool archive { get; set; }
        public string type { get; set; }
        public Nullable<bool> playlist { get; set; }
        public string embed_url { get; set; }
        public string artwork { get; set; }
    
        public virtual User User { get; set; }
    }
}
